### ISSUE TITLE
kde-extraapps cannot be build because of missing depends.

### ISSUE THREAD

**Issue by FredBezies** [fluxer/kde-extraapps#1]
Hello.

I tried to build extraapps on Archlinux and I was missing some depends.

* poppler-qt4: could be find on archlinux archive
* eigen2 and qca-qt4: could be find on AUR
* qimageblitz: archlinux archive only have an i686 version.

Looks like extraapps needs a lot of love!

**Comment by fluxer** [comment]
That is correct, I will prepare package files for them. Thanks for reporting the issue.

**Comment by fluxer** [comment]
The Qt4 backend is no longer maintained upstream so somoene will have to step up for that or building some sub-projects (like Okular) will not be possible and they will have to be made optional and not build by default atleast for now.

**Comment by fluxer** [comment]
I've added qimageblitz and qca-qt4 package filess to the main repository. I will leave the issue open becase poppler is still on the TODO and since it is optional I've changed the package files to not require it for now. Building from the provided package files should possible now (I am building packages right now).

Cheers!

**Comment by FredBezies** [comment]
New missing dependency: liblastfm. Archlinux is only providing qt5 based one now.

**Comment by fluxer** [comment]
Hi,

I added package files for both via https://github.com/fluxer/katana/commit/6522554e0bc5d6d98dc16d76b552f7efbd903ee9. Thanks for reporting the issue.

Cheers!
